### ISSUE TITLE
Provide configuration independently of a site

### ISSUE THREAD

**Issue by brotkrueml** [brotkrueml/typo3-matomo-widgets#41]
### Is your feature request related to a problem? Please describe.

For some uses cases it my be desirable to store the Matomo Widgets configuration not in the site configuration but in a dedicated folder:

- A TYPO3 site uses more than one Matomo tracker. With a configuration independent of the site, widgets from a second or third Matomo instance can be displayed.
- Using one Matomo site ID for multiple sites in a TYPO3 installation. It can be achieved now by adding the Matomo configuration to a random site configuration. But this way, the configuration of Matomo Widgets is site-independent.
- Reports for a Matomo site can be displayed when no TYPO3 site is available for.

### Describe the solution you'd like

Additionally to reading the Matomo Widgets configuration out of `config/sites/*/config.yaml` it is also possible to add one or more configurations into `config/matomo_widgets/*.yaml`. The filename does not matter. The configurations from the sites and the new folder are read and the according widgets depending on the configuration are registered.

The format of that YAML file is the same as in the site configuration, for example:

```yaml
matomoWidgetsActiveWidgets: 'actionsPerDay,actionsPerMonth'
matomoWidgetsIdSite: 1
matomoWidgetsPagesNotFoundTemplate: 'Error {statusCode} | Path = {path} | From = {referrer}'
matomoWidgetsTitle: ''
matomoWidgetsTokenAuth: '%env(EXT_MATOMOWIDGETS_TOKENAUTH)%'
matomoWidgetsUrl: 'https://matomo.example.com/'
```

Each file holds only one configuration for a Matomo instance. A Matomo Integration configuration is ignored in this case (as it is bound to a site). So a reference to the Matomo URL and site ID from Matomo Integration is not possible.

### Teachability, Documentation, Adoption, Migration Strategy

The change is to be done in the ConfigurationsFinder:
https://github.com/brotkrueml/typo3-matomo-widgets/blob/main/Classes/Configuration/ConfigurationFinder.php#L38-L40
The paths are merged and then iterated over to register the concrete widgets.

### Acceptance criteria

- [x] Matomo Widgets configurations under `config/matomo_widgets/` are taken into account.
- [x] The documentation describes this feature.
- [x] A changelog feature entry is available.
- [ ] The feature is available in version 1 and 2 of the extension.
